### PR TITLE
Feature: event for an account being deleted but still in the database

### PR DESCRIPTION
**Pull request by GhitaB**
The problem/solution is described here: https://stackoverflow.com/questions/48297612/plone-notify-a-user-on-deleting-his-account/48302367

Please test my code, I just copy-pasted from my solution based on intuition. MrTango suggested to create a PR here, so here it is.

### CODE REVIEW

**Comment by GhitaB** [comment]
If someone like this ^ please PR for me. Too many steps for so little code. :)

**Comment by GhitaB** [comment]
Also wrong link here for pdf file (The Plone Contributor Agreement can be found at): https://docs.plone.org/develop/coredev/docs/contributors_agreement_explained.html#id1

**Comment by jensens** [comment]
@GhitaB sorry for the trouble with the CLA. Unfortunately we can not get around this legal stuff. 

I like the idea firering an event before the user actually is removed. In my opinion this should go directly upstream into https://github.com/zopefoundation/Products.PluggableAuthService/blob/master/Products/PluggableAuthService/interfaces/events.py and should not end up in the already too fat PlonePAS layer.

I`am curious about opinions here @dataflake @icemac ?

**Comment by icemac** [comment]
If the event will be used in `PluggableAuthService`, too, it should go there. If it will be a `PlonePAS` only event it should live in `PlonePAS`. I actually know `PluggableAuthService` too little to be able to tell if it will make sense there or even if there is something like this event.

**Comment by jensens** [comment]
There was no activity on this for a while. I close this request for now. If you plan to work further on this please reopen and go on.

**Pull request closed without merging**
