### PR TITLE
support prefetching of users and groups

### PR DESCRIPTION
**Pull request by chaoflow**
For example for the sharing view in combination with LDAP it is very expensive to fetch user and group information with individual requests. To solve this we implemented for 4teamwork the possibility to prefetch users and groups for PAS plugins that support it.

relates:
- https://github.com/plone/plone.app.workflow/pull/9
- https://github.com/collective/Products.PloneLDAP/pull/7

### CODE REVIEW

**Comment by chaoflow** [comment]
@jensens The performance improvement of this and the related pull requests is significant and it would be a pity if they don't make it into plone. It seems it lacks somebody reviewing it. Not sure who should/could provide a schedule.

cc @jone

**Comment by djay** [comment]
@chaoflow Any pros and cons for this? Some timings maybe? I think this change would really help us but it would be good to know if there are any knock on affects and any alternatives?

**Comment by chaoflow** [comment]
@jone do you have input on the performance and any feedback from using the code?

**Comment by jensens** [comment]
There was no activity on this for a while. I close this request for now. If you plan to work further on this please reopen and go on.

**Comment by jensens** [comment]
There was no activity on this for a while. I close this request for now. If you plan to work further on this please reopen and go on.

**Pull request closed without merging**
