### PR TITLE
Back-port fix for issue #27

### PR DESCRIPTION
**Pull request by ericof**
- Notify PropertiesUpdated event when member properties are changed
  [ezvirtual]

- Add simple test for PropertiesUpdated event
  [ezvirtual]

### CODE REVIEW

**Comment by ericof** [comment]
@jenkins-plone-org please run jobs

**Comment by ericof** [comment]
@mauritsvanrees, @pbauer: Any idea why do I get [this error](https://jenkins.plone.org/job/pull-request-5.2/714/) on plone.app.redirector with Python 2.7? (Running the tests locally I get no issues)

**Comment by mauritsvanrees** [comment]
> Rebuilding the structure for migration takes too long: 0.12 seconds (max 0.1)

I have seen this a few times recently. Maybe it more easily happens when multiple PR jobs are being run in parallel, making the test slower.
I added those performance tests. They are useful to have when refactoring the code and adding new features, like I did for Plone 5.2. And they should be kept. But I think it is fine to lower the bar.
Let me create a PR for that.

**Comment by ericof** [comment]
Perfect. Let me know what to do with this PR. (Should I rerun the failed job, or commit something just to be sure it picks the correct buildout.coredev and dependencies?)

**Comment by mauritsvanrees** [comment]
I have restarted your job, running now here: https://jenkins.plone.org/job/pull-request-5.2/715/

BTW, I have not looked at the contents of this PR.

**Comment by mauritsvanrees** [comment]
The automatic check for the contributor agreement fails, but the [original PR](https://github.com/plone/Products.PlonePAS/pull/35) for 5.x was apparently fine, and the current PR is a forward port of that, so I think we can ignore this check.

Can be merged once the last job is green.

**Comment by mauritsvanrees** [comment]
Let me merge this. I have merged the performance test improvement, so the next run will obviously pass.

**Pull request merged**
