### PR TITLE
Fix login on sites without a location property

### PR DESCRIPTION
**Pull request by MatthewWilkes**
Fix https://github.com/plone/Products.CMFPlone/issues/1725

Allow log-in on sites that do not have a location membership property.

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
Looks good, thanks.
But can you do this for the other properties too? fullname, description, language, and home_page will have the same problem if someone removes them.

**Comment by MatthewWilkes** [comment]
home_page definitely, I just got bit by that this morning. Are full name and description removable?Better safe than sorry, I guess.

**Comment by mauritsvanrees** [comment]
Probably a thousand other things go wrong if someone manages to remove the fullname property, but my idea indeed was: better safe than sorry.

**Comment by MatthewWilkes** [comment]
Right, changed!

**Comment by mauritsvanrees** [comment]
It fails with error message `'' != None` in `testGetMemberInfoViewForAnonymous`.  There it expects None as fullname for anonymous users. I guess it is fine to adjust the test to expect an empty string, which is also what happens in `testGetMemberInfoViewForNonMember`:

https://github.com/plone/Products.PlonePAS/blob/7a8b6f76c50aa005c7b7924a10eeb642ed9ebf21/src/Products/PlonePAS/tests/test_membershiptool.py#L940-L956

**Comment by MatthewWilkes** [comment]
Indeed, I kicked this off at a slow point at work, need to go back in and fix it when I get a minutes.

**Comment by MatthewWilkes** [comment]
Fixed and pushed, tests running.

**Pull request merged**
