### PR TITLE
pep8 et al, review and code modernization, zca and security decorators, remove Plone4+Py2.6 code, overhaul

### PR DESCRIPTION
**Pull request by jensens**
so i did a bit code review here to see what PlonePAS actually does and while at the code i quickly did basic pep8 and formatting, decorators for zca and class security, removed some dead code and added some questions to the issue tracker here -  so some housekeeping was done.  

Seems like tests are passing (at least on my machine for coredev5). There were no functional changes.

### CODE REVIEW

**Comment by jensens** [comment]
tests are passing, meanwhile more cleanup was done. it targets Plone 5 only since Plone 4 sits on the 4.1.x branch. so its ready for merge. 
This is now a better base for further refactoring in order to get rid of the patches.

**Comment by saily** [comment]
Please add `p.a.codeanalysis`

**Comment by jensens** [comment]
This means it needs an own buildout. but +1

**Comment by gforcada** [comment]
Can we squash together all pep8 and such related commits? That would make a nicer history for later generations (of ourselves :)

**Comment by tisto** [comment]
@gforcada which reminds me that you wanted to write some git pull request best practices ;)

**Comment by jensens** [comment]
well, folks, really? I dont think this is easy to do after such a bunch of changes and is it worth the effort?

**Comment by jensens** [comment]
btw, i propose to make it easier to contribute not to add barriers

**Comment by jensens** [comment]
and btw.2.: i already squashed some of the pep8 commits together, but only those in sequence.

**Comment by adamcheasley** [comment]
+1 for a pull request best practices document. I agree it should be easy for people to contribute, but it's a balance between making it easy for people to contribute and making it easy for people to review a pull request.

**Comment by jensens** [comment]
reviewing pull requests is not easier with fewer commits. in fact i reviewed a whole bunch of them in the last months and i prefer two have semantic commits, one after another, so i can check each for its intend and validity. but if there are three pep8 addressing commits in sequence a squash is nice, but not mandatory. So I squashed those in sequence already here.

**Comment by saily** [comment]
+1 for reviewing and merging and not just claiming around. Open an issue if you want a pull-guidelines document.

**Comment by adamcheasley** [comment]
@jensens I guess it depends on the commits and the logic in their order. Fewer commits doesn't always mean that reviewing is easier, but many commits adjusting code back and forth, or like you say, numerous pep8 commits can make life more difficult. 

I'm not picking on this pull request in particular, but I think if it's worth having guidelines on code style then it's worth having guidelines on how one might structure a pull request.

**Comment by jensens** [comment]
@adamcheasley ok, so we should move the discussion over to plone.api or documentation?

**Comment by adamcheasley** [comment]
@jensens I think documentation might be a good place for it.

**Comment by gforcada** [comment]
@tisto will try to write something during the upcoming sprint, promise!

**Comment by jensens** [comment]
or wait, dont revert, rebase worked finally it seems.

**Comment by saily** [comment]
Jens is one of the most experienced Plone developers, so i trust this is ok, and if not, tisto reverts anyway

**Comment by jensens** [comment]
lol, thanks Daniel

**Comment by tisto** [comment]
@gforcada Awesome!

**Pull request merged**
