### PR TITLE
Notify new IGroupDeletedEvent when deleting a group.

### PR DESCRIPTION
**Pull request by DieKatze**
Linked to [Products.PluggableAuthService](https://github.com/zopefoundation/Products.PluggableAuthService/pull/3).

### CODE REVIEW

**Comment by jensens** [comment]
Thank you for your contribution! In order to merge this Pull Request the Plone Foundation requires a Contributor Agreement from you. I can not find you in the list of contributors. This may be by accident and we forgot to add you there or because you never signed the contributor agreement. In first case send an e-mail to agreements@plone.org referencing this issue. In second case please visit https://plone.org/foundation/contributors-agreement and follow the instructions to become an Plone core contributor. Sorry for any inconvenience.

**Comment by DieKatze** [comment]
Hi,

No problem, I forgot to do it during the Bucharest Conference so I'm the one who is sorry for the inconvenience. This omission is now fixed as I just sent my contributor agreement 5 minutes ago.

Have a nice day,

Vivian.

**Comment by DieKatze** [comment]
Hi again,

As I now belong to the big Plone family, may I humbly ask you to reconsider this pull request?

Thank you very much.

Vivian.

**Comment by gforcada** [comment]
@DieKatze welcome!

The other pull request needs to be merged as well for this pull request to work. Could you look into that as well?

**Comment by laulaz** [comment]
The other pull request has been merged.

**Comment by DieKatze** [comment]
@gforcada Thank you!

As laulaz said it, the other pull request has been merged :).

**Comment by mauritsvanrees** [comment]
@DieKatze I have merged it. Thanks for your contribution.
(I have added Products.PlonePAS to the coredev 5 checkouts.cfg one commit later.)

BTW, the Plone organisation is not listed on your profile. I do see you in the members list now. If you want to, you can edit your membership and make it publicly visible. But that's up to you.

**Pull request merged**
