### PR TITLE
Fix deprecated imports

### PR DESCRIPTION
**Pull request by thet**

### CODE REVIEW

**Comment by thet** [comment]
@jenkins-plone-org please run jobs

**Comment by thet** [comment]
Done @mauritsvanrees

**Comment by mauritsvanrees** [comment]
Actually, the tests were passing on Jenkins before your last commit, and this last commit was only about Travis. So for me it is green.

The PR title has "WIP" in it though. Is that still accurate?
And can you change the title to something more informative? :-) The first commit message seems good: "Plone 5.2 compatibility: fix deprecated imports".

**Comment by thet** [comment]
@mauritsvanrees I changed the title.
I was also thinking of removing the travis config. This is already being tested by Jenkins, so I don't see a point in testing it on Travis too.
Which repos should be tested by travis and which not? Addons?

There is some dysfunctional travis config in the "Services" section of this repositories settings, though... But obviously it's not working. I guess, I'll remove the travis config...?

**Comment by mauritsvanrees** [comment]
When a package is in Plone core, it is fine to be tested on Jenkins only. Exception may be a branch that is not used in core, like [`plone.app.contenttypes` 1.1.x](https://github.com/plone/plone.app.contenttypes/issues/404)  which is for Plone 4.3, when it was not yet in core.
Another exception would be a package that may be useful outside of Plone, especially if the tests run much faster on Travis. Or a package that we want to test in other combinations (testing plone.protect 3.x with the csrf fixes on Plone 4.3 would be good).

Fine with me to remove the travis config here.

**Comment by thet** [comment]
Thanks for the explanation. That makes much sense.

**Pull request merged**
