### PR TITLE
Pillow 8 support

### PR DESCRIPTION
**Pull request by jensens**
see https://github.com/plone/buildout.coredev/pull/687

### CODE REVIEW

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
We should branch away for Py3/Plone 6 only here.

**Review by mauritsvanrees — APPROVED** [review]
I confirm this fixes the failure with Pillow 8.

> We should branch away for Py3/Plone 6 only here.

Why?  This change works fine on 2.7 as well, and is only a change in the test code.
At some point we should drop 2.7/5.2, but for now it seems okay.

**Comment by mauritsvanrees** [comment]
Ah, the 2.7 PR job failed with an unrelated error, but also an actual error in PlonePAS, but this was somehow  not reported in the summary. So after merge, the 5.2-2.7 job fails:

```
File "/home/jenkins/workspace/plone-5.2-python-2.7/src/Products.PlonePAS/src/Products/PlonePAS/utils.py", line 65, in Products.PlonePAS.utils.scale_image
Failed example:
    sneaky = BytesIO('��<div>Evil!!!</div>'.encode("utf-8"))
Exception raised:
    Traceback (most recent call last):
      File "/srv/python2.7/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest Products.PlonePAS.utils.scale_image[12]>", line 1, in <module>
        sneaky = BytesIO('��<div>Evil!!!</div>'.encode("utf-8"))
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 0: ordinal not in range(128)
```

I see why you wanted to branch away for Py3/Plone 6 only here.
Putting effort into UnicodeDecodeErrors for 2.7 is not what I want.
I will create a branch 6.x and use that in coredev 5.2.

**Comment by mauritsvanrees** [comment]
All done.

**Pull request merged**
